---
name: main

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
}
      - name: Build 
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: awxkit_base:latest
          push: false
